microblaze: Add prlimit64 to syscalls.list
Prevents undefined reference to `prlimit64' when linking to libc.so.6

Comparing to powerpc, we also seem to be missing fanotify_mark

Signed-off-by: David Holsgrove <david.holsgrove@petalogix.com>